modLoader="javafml"
loaderVersion="[31,)"
[[mods]]
modId="chineseworkshop"
version="${file.jarVersion}"
displayName="ChineseWorkshop"
authors="CityOfSkyTCD, Snownee"
displayURL="https://minecraft.curseforge.com/projects/chineseworkshop"
logoFile="logo.png"
description='''
'''

[[dependencies.chineseworkshop]]
    modId="kiwi"
    mandatory=true
    versionRange="[2.7.2, 2.11)"
    ordering="BEFORE"
    side="BOTH"
