modLoader="javafml"
loaderVersion="[34,)"
license="ARR"

[[mods]]
modId="chineseworkshop"
version="${file.jarVersion}"
displayName="ChineseWorkshop"
authors="CityOfSkyTCD, Snownee"
displayURL="https://www.curseforge.com/minecraft/mc-mods/chineseworkshop"
description='''
'''

[[dependencies.chineseworkshop]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.4, 3.10)"
    ordering="BEFORE"
    side="BOTH"
