modLoader="javafml"
loaderVersion="[32,)"
[[mods]]
modId="chineseworkshop"
version="${file.jarVersion}"
displayName="ChineseWorkshop"
authors="CityOfSkyTCD, Snownee"
displayURL="https://minecraft.curseforge.com/projects/chineseworkshop"
logoFile="logo.png"
description='''
'''

[[dependencies.chineseworkshop]]
    modId="kiwi"
    mandatory=true
    versionRange="[3.1.3, 3.7)"
    ordering="BEFORE"
    side="BOTH"
